' Gambas module file

PUBLIC SUB Main()

IF System.User.Name <> "root" THEN
   PRINT "You need to be root to run " & Application.Title & "..."
   Utils.logMessage("You need to be root to run " & Application.Title & "...")
ELSE
   ' Check for vcpufreq-load enabled:
   Utils.ReadConfig
   IF Global.vCPUFreqConfExists = TRUE THEN
      IF Global.vCPUFreqLoad = TRUE THEN
         ' Load saved cpu-freq config:
         PRINT "vcpufreq-loader enabled in config..."
         Utils.logMessage("vcpufreq-loader enabled in config...")
         Utils.SetConfig
      ELSE
         PRINT "vcpufreq-loader disabled in config..."
         Utils.logMessage("vcpufreq-loader disabled in config...")
      ENDIF
   ENDIF
ENDIF

END
